//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B4.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bai4TTNEntities : DbContext
    {
        public Bai4TTNEntities()
            : base("name=Bai4TTNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail_PN> Detail_PN { get; set; }
        public virtual DbSet<Detail_PX> Detail_PX { get; set; }
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
