//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B4.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public string Ma_PN { get; set; }
        public Nullable<System.DateTime> Ngay_nhap { get; set; }
        public string Ma_kho { get; set; }
    
        public virtual Detail_PN Detail_PN { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
